### ISSUE TITLE
Not and issue just a comment

### ISSUE THREAD

**Issue by mathieu-aubin** [LukeShirnia/OOM-Killer-score#1]
Found this pretty nice so i added it to [_c7repos_](https://c7repos.4ce.ca) as a function called 'checkOOM'. It's basically the same as what you wrote except i added escapes to each of the different commands since i deal with a huge amount of hosts and some commands are aliased to very specific stuff in some places. Anyways, figured you'd like to know.

cool thing. thanks

I have given proper credits i believe.

Please close this :+1:

**Comment by LukeShirnia** [comment]
Hi @mathieu-aubin 
Sorry I honestly don't know how I've only just seen this. Thanks for the heads up and reference!
I've actually just rewritten it in python as it's a little more friendly on a stressed system and runs a lot faster.
I'm going to throw it into the rewrite of my [oom-analyser](https://github.com/LukeShirnia/out-of-memory) soon as that whole thing is due an update.
I'll close this now.
